### ISSUE TITLE
Error (fixed) in make with OpenSSH package

### ISSUE THREAD

**Issue by cgeeb** [8devices/carambola2#22]
After a feeds update today, my previously solid build failed with the following error when compiling OpenSSH:

mac.c:73:33: error: 'EVP_ripemd160' undeclared here (not in a function)
make[4]: *** [mac.o] Error 1
make[4]: Leaving directory `/home/chris/workspace/carambola2/build_dir/target-mips_r2_uClibc-0.9.33.2/openssh-without-pam/openssh-6.4p1'
make[3]: *** [/home/chris/workspace/carambola2/build_dir/target-mips_r2_uClibc-0.9.33.2/openssh-without-pam/openssh-6.4p1/.built] Error 2
make[3]: Leaving directory `/home/chris/workspace/carambola2/feeds/packages/net/openssh'
make[2]: *** [package/feeds/packages/openssh/compile] Error 2
make[2]: Leaving directory `/home/chris/workspace/carambola2'
make[1]: *** [/home/chris/workspace/carambola2/staging_dir/target-mips_r2_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/chris/workspace/carambola2'
make: *** [world] Error 2

I found the fix in an Arduino forum
http://forum.arduino.cc/index.php?PHPSESSID=i7hk3o9pr5mrfff79t8fm9ac82&topic=187938.msg1570534#msg1570534

1. copy "110-no_ripemd_fix.patch" into package/feeds/packages/openssh/
2. compile opens alone "make package/feeds/packages/openssh/compile V=s"

"110-no_ripemd_fix.patch" is from openwrt main stream.
https://dev.openwrt.org/browser/packages/net/openssh/patches/110-no_ripemd_fix.patch?rev=38693

I downloaded the patch, copied it into the directory above, recompiled and it was all fine.
I wanted to share this solution with the community.

**Comment by mantas-p** [comment]
This is probably obsolete now.
