### ISSUE TITLE
Wifi interface not working

### ISSUE THREAD

**Issue by gantor2000** [8devices/carambola2#25]
During startup i get the message:
## 

[   59.220000] ath: phy0: eeprom contains invalid mac address: 9b:db:52:32:c8:24
[   59.230000] ath: phy0: random mac address will be used: e6:fe:f2:92:97:e5
[   59.240000] ath: Invalid EEPROM contents
[   59.240000] ath9k ar933x_wmac: failed to initialize device
## [   59.240000] ath9k: probe of ar933x_wmac failed with error -22

i just installed the firmware upgrade (http://pkg.8devices.com/v2.5/carambola2/openwrt-ar71xx-generic-carambola2-squashfs-sysupgrade.bin) 

but the error still exists.

**Comment by codan-soea** [comment]
Is EEPROM address the same for Lima?

**Comment by Juwaed** [comment]
.

**Comment by KHALED306** [comment]
حجر هاشمي هيصم
https://www.dekorishn-altheqa.com/modern-stone-2/
واجهات منازل حجر هاشمي
https://www.dekorishn-altheqa.com/decoration/
واجهات فلل حجر هاشمى
https://www.dekorishn-altheqa.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D9%81%D9%84%D9%84-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%8A/
واجهات عمارات حجر هاشمي هيصم
https://www.dekorishn-altheqa.com/houses-design/

**Comment by KHALED306** [comment]
واجهات حجر هاشمى
https://www.decoration-altheqa.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D9%81%D9%84%D9%84-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89/
احدث انواع ديكورات حجر هاشمى
https://www.decoration-altheqa.com/%D8%A3%D8%AD%D8%AF%D8%AB-%D8%A3%D9%86%D9%88%D8%A7%D8%B9-%D8%AF%D9%8A%D9%83%D9%88%D8%B1%D8%A7%D8%AA-%D8%A7%D9%84%D8%AD%D8%AC%D8%B1-%D8%A7%D9%84%D9%87%D8%A7%D8%B4%D9%85%D9%8A/
واجهات حجر هاشمى هيصم
https://www.decoration-altheqa.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5%D9%85/
واجهات حجر ابيض ازازي
https://www.decoration-altheqa.com/white-stone-facades/

**Comment by KHALED306** [comment]
شركه حجر هاشمى 
https://www.altheqa-eg.com/%D8%B4%D8%B1%D9%83%D8%A9-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89/
واجهات منازل حجر هاشمي
https://www.altheqa-eg.com/modern-homes/
تركيب حجر هاشمى هيصم خطوه بخطوه
https://www.altheqa-eg.com/%D8%AA%D8%B1%D9%83%D9%8A%D8%A8-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5%D9%85-%D8%AE%D8%B7%D9%88%D8%A9-%D8%A8%D8%AE%D8%B7%D9%88%D8%A9/
انواع الحجر الهاشمي
https://www.altheqa-eg.com/stone-types/
اسعار الحجر الهاشمى 
https://www.altheqa-eg.com/stone-prices/
اسعار القرميد 
https://www.altheqa-eg.com/prices-qarmid/ 
انواع القرميد	
https://www.altheqa-eg.com/types-qarmid/ 
واجهات فلل حجر هاشمى 
https://www.altheqa-eg.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D9%81%D9%84%D9%84-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D8%A8%D8%A7%D9%84%D8%B5%D9%88%D8%B1-%D9%88%D8%A7%D9%84%D9%81%D8%AF%D9%8A%D9%88%D9%87%D8%A7/
احدث مقالات حجر هاشمى 
https://www.altheqa-eg.com/%D8%A7%D8%AD%D8%AF%D8%AB-%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89/
اهم الشركات لتركيب حجر هاشمي هيصم
https://www.altheqa-eg.com/%D8%A3%D9%87%D9%85-%D8%A7%D9%84%D8%B4%D8%B1%D9%83%D8%A7%D8%AA-%D9%84%D9%88%D8%B8%D9%8A%D9%81%D8%A9-%D8%AA%D8%B1%D9%83%D9%8A%D8%A8-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5/
واجهات الحجر الفرعونى VS واجهات الحجر الهاشمي 
https://www.altheqa-eg.com/%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%87%d8%a7%d8%b4%d9%85%d9%8a-vs-%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%81/
واجهات منازل حجر طبيعي
https://www.altheqa-eg.com/home/
واجهات حجر هاشمي
https://www.altheqa-eg.com/%d8%aa%d8%b4%d9%83%d9%8a%d9%84%d8%a7%d8%aa-%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%87%d8%a7%d8%b4%d9%85%d9%8a-%d9%81%d9%8a-%d8%a3%d8%b9%d9%85%d8%a7%d9%84-%d8%a7%d9%84%d8%aa%d8%b4%d8%b7%d9%8a/
ارقام افضل شركات تركيب حجر فرعونى
https://www.altheqa-eg.com/%d8%a3%d8%b1%d9%82%d8%a7%d9%85-%d8%a3%d9%81%d8%b6%d9%84-%d8%b4%d8%b1%d9%83%d8%a7%d8%aa-%d8%aa%d8%b1%d9%83%d9%8a%d8%a8-%d8%ad%d8%ac%d8%b1-%d9%81%d8%b1%d8%b9%d9%88%d9%86%d9%8a/
تنفيذ واجهات منازل بالحجر الفرعونى باحدث الاشكال
https://www.altheqa-eg.com/%d8%aa%d9%86%d9%81%d9%8a%d8%b0-%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d9%85%d9%86%d8%a7%d8%b2%d9%84-%d8%a8%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%81%d8%b1%d8%b9%d9%88%d9%86%d9%89-%d8%a8%d8%a7/
ما الفرق بين سعر الحجر الهاشمى فرز اول والحجر الهاشمى فرز ثانى
https://www.altheqa-eg.com/how-much-is-a-stone/
تصميمات كلاسكيه لاحجار الفرعونية
https://www.altheqa-eg.com/%d8%aa%d8%b5%d9%85%d9%8a%d9%85%d8%a7%d8%aa-%d9%83%d9%84%d8%a7%d8%b3%d9%8a%d9%83%d9%8a%d8%a9-%d9%84%d9%84%d8%a3%d8%ad%d8%ac%d8%a7%d8%b1-%d8%a7%d9%84%d9%81%d8%b1%d8%b9%d9%88%d9%86%d9%8a%d8%a9/
 واجهات حجر 
https://www.altheqa-eg.com/category/hachemi-stone/page/2/
تدبيش
https://www.altheqa-eg.com/category/dabash/
ارضيات حجر بازلت
https://www.altheqa-eg.com/category/basalt-stone-flooring/
شركة الثقه للمقاولات
https://www.altheqa-eg.com/
اسعار الحجر الابيض الازازي ,سعر متر الحجر الابيض الازازي
https://www.altheqa-eg.com/azazi-white-stone/
اسعار البازلت فى مصر
https://www.altheqa-eg.com/%D8%A7%D8%B3%D8%B9%D8%A7%D8%B1-%D8%A7%D9%84%D8%A8%D8%A7%D8%B2%D9%84%D8%AA-%D9%81%D9%89-%D9%85%D8%B5%D8%B1-%D8%B4%D8%BA%D9%84-%D9%85%D8%B5%D9%86%D8%B9/
حجر بازلت
https://www.altheqa-eg.com/%D8%A7%D8%B4%D9%83%D8%A7%D9%84-%D8%AD%D8%AC%D8%B1-%D8%A7%D9%84%D8%A8%D8%A7%D8%B2%D9%84%D8%AA-%D8%A8%D8%A7%D9%84%D8%B5%D9%88%D8%B1/
حجر بازلت اسود
https://www.altheqa-eg.com/%D8%AA%D8%B1%D9%83%D9%8A%D8%A8-%D8%AD%D8%AC%D8%B1-%D8%A8%D8%A7%D8%B2%D9%84%D8%AA-%D8%A7%D8%B3%D9%88%D8%AF/
مقاسات حجر بازلت
https://www.altheqa-eg.com/basalt-sizes/
تركيب حجر بازلت
https://www.altheqa-eg.com/the-price-of-basalt/ 
حجر بازلت
https://www.altheqa-eg.com/%d8%ad%d8%ac%d8%b1-%d8%a8%d8%a7%d8%b2%d9%84%d8%aa-%d9%85%d9%88%d8%a7%d8%b5%d9%81%d8%a7%d8%aa-%d9%88%d8%a7%d8%b3%d8%b9%d8%a7%d8%b1/ 
واجهات حجر هاشمى ابيض ازازي
https://www.altheqa-eg.com/%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%ad%d8%ac%d8%b1-%d9%87%d8%a7%d8%b4%d9%85%d9%89-%d8%a3%d8%a8%d9%8a%d8%b6-%d8%a7%d8%b2%d8%a7%d8%b2%d9%8a/
ارضيات رخام
https://www.altheqa-eg.com/%d8%a3%d9%87%d9%85-%d8%a7%d8%b3%d8%aa%d8%ae%d8%af%d8%a7%d9%85%d8%a7%d8%aa-%d8%a7%d9%84%d8%b1%d8%ae%d8%a7%d9%85-%d9%81%d9%89-%d8%a7%d9%84%d8%a7%d8%b1%d8%b6%d9%8a%d8%a7%d8%aa-%d9%88%d8%a7%d9%84%d9%88/
حجر بازلت عباسية
https://www.altheqa-eg.com/%D8%A7%D8%B4%D9%83%D8%A7%D9%84-%D9%88%D8%A7%D9%86%D9%88%D8%A7%D8%B9-%D8%AD%D8%AC%D8%B1-%D8%A7%D9%84%D8%A8%D8%A7%D8%B2%D9%84%D8%AA-%D9%88%D8%A7%D8%B3%D8%B9%D8%A7%D8%B1-%D8%A7%D9%84%D8%AA%D9%88%D8%B1/
تركيب ارضيات حجر بازلت
https://www.altheqa-eg.com/%d9%85%d9%85%d9%8a%d8%b2%d8%a7%d8%aa-%d8%aa%d8%b1%d9%83%d9%8a%d8%a8-%d8%a3%d8%b1%d8%b6%d9%8a%d8%a7%d8%aa-%d8%ad%d8%ac%d8%b1-%d8%a8%d8%a7%d8%b2%d9%84%d8%aa/
اشكال واجهات بيوت
https://www.altheqa-eg.com/%d8%a3%d8%b4%d9%83%d8%a7%d9%84-%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%a8%d9%8a%d9%88%d8%aa-%d8%a8%d8%aa%d8%b5%d9%85%d9%8a%d9%85%d8%a7%d8%aa-%d9%81%d8%b1%d8%b9%d9%88%d9%86%d9%8a%d8%a9/
افضل شركة واجهات حجر هاشمي
https://www.altheqa-eg.com/%d8%a3%d9%81%d8%b6%d9%84-%d8%b4%d8%b1%d9%83%d8%a9-%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%ad%d8%ac%d8%b1-%d9%87%d8%a7%d8%b4%d9%85%d9%8a/
حجر هاشمي هيصم
https://www.altheqa-eg.com/%d8%ad%d8%ac%d8%b1-%d9%87%d8%a7%d8%b4%d9%85%d9%89-%d9%87%d9%8a%d8%b5%d9%85-%d9%87%d9%88-%d8%a7%d9%84%d8%a7%d9%81%d8%b6%d9%84-%d8%af%d8%a7%d8%a6%d9%85%d8%a7-%d9%84%d9%85%d8%a7%d8%b0%d8%a7%d8%9f/

**Comment by KHALED306** [comment]
واجهات حجر | حجر هاشمى هيصم
https://www.altheqa-stone.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5%D9%85/
واجهات حجر هاشمى
https://www.decoration-altheqa.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D9%81%D9%84%D9%84-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89/
واجهات حجر هاشمى هيصم
https://www.decoration-altheqa.com/%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5%D9%85/
حجر هاشمى هيصم
https://www.altheqa-stone.com/category/hism-stone/
معرض صور حجر هاشمى
https://www.altheqa-stone.com/stone-decorations//
واجهات منازل حجر ابيض ازازي
https://www.altheqa-stone.com/white-stone/
ديكورات حجر هاشمي
https://www.altheqa-stone.com/stone-3/ 
ديكورات حجر هاشمي
https://www.altheqa-stone.com/%D9%81%D9%86-%D8%A7%D8%AE%D8%AA%D9%8A%D8%A7%D8%B1-%D8%AF%D9%8A%D9%83%D9%88%D8%B1%D8%A7%D8%AA-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%8A/ 
تشطيب واجهات منازل
https://www.altheqa-stone.com/%D8%A3%D8%B4%D9%83%D8%A7%D9%84-%D8%AA%D8%B4%D8%B7%D9%8A%D8%A8-%D9%88%D8%A7%D8%AC%D9%87%D8%A7%D8%AA-%D9%85%D9%86%D8%A7%D8%B2%D9%84-%D9%85%D9%85%D9%8A%D8%B2%D8%A9/ 
نصائح فى تركيب الحجر الهاشمى
https://www.altheqa-stone.com/%D9%86%D8%B5%D8%A7%D8%A6%D8%AD-%D9%81%D9%89-%D8%AA%D8%B1%D9%83%D9%8A%D8%A8-%D8%A7%D9%84%D8%AD%D8%AC%D8%B1-%D8%A7%D9%84%D9%87%D8%A7%D8%B4%D9%85%D9%89/
تعرف على اسعار الحجر الهاشمى فى مصر باشكاله المختلفه
https://www.altheqa-stone.com/hashmi-stone-prices/
سعر حجر هاشمى هيصم وطريقة تركيبه
https://www.altheqa-stone.com/%D8%B3%D8%B9%D8%B1-%D8%AD%D8%AC%D8%B1-%D9%87%D8%A7%D8%B4%D9%85%D9%89-%D9%87%D9%8A%D8%B5%D9%85-%D9%88%D8%B7%D8%B1%D9%8A%D9%82%D9%87-%D8%AA%D8%B1%D9%83%D9%8A%D8%A8%D8%A9/
تصميم جدران المنازل بالحجر الهاشمى
https://www.altheqa-stone.com/%d8%aa%d8%b5%d9%85%d9%8a%d9%85-%d8%ac%d8%af%d8%b1%d8%a7%d9%86-%d8%a7%d9%84%d9%85%d9%86%d8%a7%d8%b2%d9%84-%d8%a8%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%87%d8%a7%d8%b4%d9%85%d9%8a/
لماذا واجهات حجر هاشمى تكلف اموال كثيره
https://www.altheqa-stone.com/%d9%84%d9%85%d8%a7%d8%b0%d8%a7-%d9%88%d8%a7%d8%ac%d9%87%d8%a7%d8%aa-%d8%ad%d8%ac%d8%b1-%d9%87%d8%a7%d8%b4%d9%85%d9%89-%d8%aa%d9%83%d9%84%d9%81-%d8%a7%d9%85%d9%88%d8%a7%d9%84-%d9%83%d8%ab%d9%8a%d8%b1/
معرفه اسعار حجر هاشمى اليوم فى مصر
https://www.altheqa-stone.com/%d9%85%d8%b9%d8%b1%d9%81%d9%87-%d8%a7%d8%b3%d8%b9%d8%a7%d8%b1-%d8%ad%d8%ac%d8%b1-%d9%87%d8%a7%d8%b4%d9%85%d9%89-%d8%a7%d9%84%d9%8a%d9%88%d9%85-%d9%81%d9%89-%d9%85%d8%b5%d8%b1/
روعه الحجر الفرعونى فى الديكور المنزلى
https://www.altheqa-stone.com/%d8%b1%d9%88%d8%b9%d8%a9-%d8%a7%d9%84%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d9%81%d8%b1%d8%b9%d9%88%d9%86%d9%89-%d9%81%d9%89-%d8%a7%d9%84%d8%af%d9%8a%d9%83%d9%88%d8%b1-%d8%a7%d9%84%d9%85%d9%86%d8%b2%d9%84/
واجهات الحجر الفرعونى فى مصر وتركبيها باقل الاسعار
https://www.altheqa-stone.com/altheqa-stone/
مقالات
https://www.altheqa-stone.com/bs-front-page/
حجر بازلت
https://www.altheqa-stone.com/category/stone-basalt/
ديكورات داخلية
https://www.altheqa-stone.com/category/interior-decorations/
ديكورات خارجية
https://www.altheqa-stone.com/category/hism-stone/exterior-decorations/
دبش
https://www.altheqa-stone.com/category/%d8%af%d8%a8%d8%b4/
شوايات
https://www.altheqa-stone.com/category/grills/
اشكال حجر بازلت بالصور
https://www.altheqa-eg.com/%D8%A7%D8%B4%D9%83%D8%A7%D9%84-%D8%AD%D8%AC%D8%B1-%D8%A7%D9%84%D8%A8%D8%A7%D8%B2%D9%84%D8%AA-%D8%A8%D8%A7%D9%84%D8%B5%D9%88%D8%B1/
تصدير حجر بازلت
https://www.altheqa-stone.com/%D8%AA%D8%B5%D8%AF%D9%8A%D8%B1-%D8%AD%D8%AC%D8%B1-%D8%A8%D8%A7%D8%B2%D9%84%D8%AA/
ارضيات حجر بازلت
https://www.altheqa-stone.com/stone-basalt/
تركيب حجر بازلت
https://www.altheqa-stone.com/%D8%AA%D8%B1%D9%83%D9%8A%D8%A8-%D8%AD%D8%AC%D8%B1-%D8%A8%D8%A7%D8%B2%D9%84%D8%AA/
مقاسات حجر بازلت 
https://www.design-eg.com/basalt/

**Comment by gogoasiri80** [comment]
Gogo

**Comment by gogoasiri80** [comment]
Hhhhhh

**Comment by vishal9-star** [comment]
56:D9:E7:AD:09:2F

**Comment by Ss987654321** [comment]
لا

**Comment by Ss987654321** [comment]
ف

**Comment by 225360** [comment]
R

**Comment by 225360** [comment]
2253
