### ISSUE TITLE
After watchdog board completely hang

### ISSUE THREAD

**Issue by clagir** [8devices/carambola2#44]
Test case:
carambola2 with original image, only 3.3 V, GND, TX e RX connected.
Console monitoring via serial-2-usb converter.

Command:
pgrep watchdog | xargs kill -SIGSTOP

Carambola2 restart after watchdog timeout, but sometime hang completely 
(as per https://dev.openwrt.org/ticket/12121): nothing on console.

I can recover only by remove power e power on again.

AR9331 register seem to log watchdog correctly, and registry set with right value:
after correct wotchdog restart:    io -r -4 0x18060008      ->    18060008:  80000003
after power on:    io -r -4 0x18060008      ->    18060008:  00000003

Any ideas?

(Other case: in my board, led is connected on GPIO12 active low, thus always ON. When Carambola2 hang, led switch from ON to OFF and remain OFF until disconnect and reconnect power) 

Clagir

**Comment by Darlard** [comment]
Hello, we are experiencing this problem too, any idea about what is causing it? And how to solve it?

**Comment by metehan-observables** [comment]
Has this problem been solved?
