### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by valentt** [8devices/carambola2#47]
I have few Carambola 2 dev boards, and I haven't used this particular one for few months but not I see it shows kernel panic:

[    0.000000] Linux version 3.10.49 (zilvinas@LX-buildd3) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r42067) ) #3 Mon Aug 11 16:42:35 EEST 2014
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 00019374 (MIPS 24Kc)
[    0.000000] SoC: Atheros AR9330 rev 1
[    0.000000] Clocks: CPU:400.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:40.000MHz
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x03ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x03ffffff]
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line:  board=CARAMBOLA2 console=ttyATH0,115200 mtdparts=spi0.0:256k(u-boot)ro,64k(u-boot-env)ro,16000k(firmware),64k(art)ro rootfstype=squashfs,jffs2 noinitrd
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 61332k/65536k available (2338k kernel code, 4204k reserved, 427k data, 240k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:51
[    0.000000] Calibrating delay loop... 265.42 BogoMIPS (lpj=1327104)
[    0.080000] pid_max: default: 32768 minimum: 301
[    0.080000] Mount-cache hash table entries: 512
[    0.090000] NET: Registered protocol family 16
[    0.100000] MIPS: machine is 8devices Carambola2 board
[    0.550000] bio: create slab <bio-0> at 0
[    0.560000] Switching to clocksource MIPS
[    0.570000] NET: Registered protocol family 2
[    0.570000] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.570000] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.580000] TCP: Hash tables configured (established 512 bind 512)
[    0.580000] TCP: reno registered
[    0.580000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.590000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.600000] NET: Registered protocol family 1
[    0.620000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.630000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.640000] msgmni has been set to 119
[    0.640000] io scheduler noop registered
[    0.640000] io scheduler deadline registered (default)
[    0.650000] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.660000] ar933x-uart: ttyATH0 at MMIO 0x18020000 (irq = 11) is a AR933X UART
[    0.670000] console [ttyATH0] enabled, bootconsole disabled
[    0.670000] console [ttyATH0] enabled, bootconsole disabled
[    0.680000] ath79-spi ath79-spi: master is unqueued, this is deprecated
[    0.690000] m25p80 spi0.0: found w25q128, expected m25p80
[    0.690000] m25p80 spi0.0: w25q128 (16384 Kbytes)
[    0.700000] 4 cmdlinepart partitions found on MTD device spi0.0
[    0.700000] Creating 4 MTD partitions on "spi0.0":
[    0.710000] 0x000000000000-0x000000040000 : "u-boot"
[    0.720000] 0x000000040000-0x000000050000 : "u-boot-env"
[    0.720000] 0x000000050000-0x000000ff0000 : "firmware"
[    0.740000] 2 uimage-fw partitions found on MTD device firmware
[    0.750000] 0x000000050000-0x000000150000 : "kernel"
[    0.750000] 0x000000150000-0x000000ff0000 : "rootfs"
[    0.760000] mtd: device 4 (rootfs) set to be root filesystem
[    0.760000] 1 squashfs-split partitions found on MTD device rootfs
[    0.770000] 0x000000410000-0x000000ff0000 : "rootfs_data"
[    0.780000] 0x000000ff0000-0x000001000000 : "art"
[    0.800000] libphy: ag71xx_mdio: probed
[    1.350000] ag71xx-mdio.1: Found an AR7240/AR9330 built-in switch
[    2.380000] eth0: Atheros AG71xx at 0xba000000, irq 5, mode:GMII
[    2.930000] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd041, driver=Generic PHY]
[    2.940000] eth1: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    2.950000] TCP: cubic registered
[    2.950000] NET: Registered protocol family 17
[    2.950000] Bridge firewalling registered
[    2.960000] 8021q: 802.1Q VLAN Support v1.8

[    2.970000] VFS: Mounted root (squashfs filesystem) readonly on device 31:4.
[    2.980000] Freeing unused kernel memory: 240K (80314000 - 80350000)
[    3.550000] Reserved instruction in kernel code[#1]:
[    3.550000] CPU: 0 PID: 1 Comm: preinit Not tainted 3.10.49 #3
[    3.550000] task: 83828000 ti: 8382c000 task.ti: 8382c000
[    3.550000] $ 0   : 00000000 00000001 ffffff82 00000001
[    3.550000] $ 4   : 8382dd68 7764f000 7765e000 0007764f
[    3.550000] $ 8   : 00000000 839ee420 00000000 0007764f
[    3.550000] $12   : 00000000 00000003 00000000 00000000
[    3.550000] $16   : 8382dd68 839ee318 839ee370 8394f000
[    3.550000] $20   : ffffff80 8028a720 00000000 00000000
[    3.550000] $24   : 00000000 77671e8c  
[    3.550000] $28   : 8382c000 8382dd68 ffffff83 839ee33c
[    3.550000] Hi    : 00000002
[    3.550000] Lo    : 00000000
[    3.550000] epc   : 8c7dc801 0x8c7dc801
[    3.550000]     Not tainted
[    3.550000] ra    : 839ee33c 0x839ee33c
[    3.550000] Status: 1000f003 KERNEL EXL IE 
[    3.550000] Cause : 10800028
[    3.550000] PrId  : 00019374 (MIPS 24Kc)
[    3.550000] Modules linked in:
[    3.550000] Process preinit (pid: 1, threadinfo=8382c000, task=83828000, tls=00000000)
[    3.550000] Stack : 00000000 00000001 00000000 7764c000 839ee3c8 839ee318 7765e000 00000000
      00000000 80380000 00000001 8382de44 8382de40 800a7620 0080000c 7764f000
      00000000 0007764f 839ee3c8 839ee370 839ee328 8394f000 839ee318 7765e000
      8394f000 7765f000 7765e000 801170f4 8394f000 839ee370 839ee118 80294f08
      00000003 801d5398 00001000 00000073 7765e000 8394f000 838078c0 7765f000
      ...
[    3.550000] Call Trace:[<800a7620>] 0x800a7620
[    3.550000] [<801170f4>] 0x801170f4
[    3.550000] [<80294f08>] 0x80294f08
[    3.550000] [<801d5398>] 0x801d5398
[    3.550000] [<801aa530>] 0x801aa530
[    3.550000] [<800c23b8>] 0x800c23b8
[    3.550000] [<8014b94c>] 0x8014b94c
[    3.550000] [<80115838>] 0x80115838
[    3.550000] [<80293d34>] 0x80293d34
[    3.550000] [<8028ef90>] 0x8028ef90
[    3.550000] [<80075c50>] 0x80075c50
[    3.550000] [<800625b0>] 0x800625b0
[    3.550000] 
[    3.550000] 
Code: 0000  0000  0000 <ffff> ffff  ffff  ffff  ffff  ffff 
[    3.730000] ---[ end trace b18d1648681a9206 ]---

**Comment by thom-nic** [comment]
Curious - was this ever resolved?

**Comment by valinskas** [comment]
Closing, 5y+  since last update. No, issue was not resolved;

/sbin/preinit (pid = 1)  is terminating prematurely. Thus kernel panic.
