### ISSUE TITLE
mjpg_streamer r182 breaks yuv cameras

### ISSUE THREAD

**Issue by kisdia** [8devices/carambola2#52]
yuv webcam worked with carambola 2.5 with mjpg_streamer r181. It does not work with carambola 2.6 with mjpg_streamer r182. No other changes. Please do not use mjpg_streamer experimental.

**Comment by mantas-p** [comment]
Hi,
What exactly is not working? Does mjpg-streamer crash, or YUV option is no longer available? Can you post logs when problem happens?

**Comment by mantas-p** [comment]
Should be fixed in v2.7 release.

**Comment by kisdia** [comment]
Hi,

Thanks for looking and fixing this. Tested and works fine now.
