### ISSUE TITLE
Cant connect to Carambola AP

### ISSUE THREAD

**Issue by OortJacek** [8devices/carambola2#57]
Hi,

I have problem with connect to Carambola WiFi Access Point. 
When I am trying to connect to AP the diode on devboard is flashing and I got this logs on carambola:

**logread**
Wed Jul  8 14:22:28 2015 daemon.info hostapd: wlan0: STA ac:7b:a1:d0:39:4b IEEE 802.11: authenticated
Wed Jul  8 14:22:28 2015 daemon.info hostapd: wlan0: STA ac:7b:a1:d0:39:4b IEEE 802.11: associated (aid 1)
Wed Jul  8 14:22:28 2015 daemon.info hostapd: wlan0: STA ac:7b:a1:d0:39:4b WPA: pairwise key handshake completed (RSN)
Wed Jul  8 14:22:31 2015 daemon.info dnsmasq-dhcp[1077]: DHCPDISCOVER(wlan0) ac:7b:a1:d0:39:4b 
Wed Jul  8 14:22:31 2015 daemon.info dnsmasq-dhcp[1077]: DHCPOFFER(wlan0) 192.168.1.131 ac:7b:a1:d0:39:4b 
Wed Jul  8 14:22:33 2015 daemon.info dnsmasq-dhcp[1077]: DHCPDISCOVER(wlan0) ac:7b:a1:d0:39:4b 
Wed Jul  8 14:22:33 2015 daemon.info dnsmasq-dhcp[1077]: DHCPOFFER(wlan0) 192.168.1.131 ac:7b:a1:d0:39:4b 

But finally I am not connected. My desktop computer gives up after few second. 

_This is my configuration:_
**etc/config/wireless** :
config wifi-device  radio0
        option type     mac80211
        option channel  11
        option hwmode   11ng
        option macaddr  c4:93:00:02:cb:43
        option htmode   HT20
        list ht_capab   SHORT-GI-20
        list ht_capab   SHORT-GI-40
        list ht_capab   RX-STBC1
        list ht_capab   DSSS_CCK-40
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 0

config wifi-iface
        option device   'radio0'
        option network  'wlan0'
        option mode     'ap'
        option ssid     'Carambola'
        option encryption psk2
        option key 'xxxxxxxx'

**etc/config/network**:
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config interface 'lan'
        option ifname 'eth0'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'

config interface 'wlan0'
        option ifname 'wlan0'
        option proto 'static'
        option ipaddr '192.168.1.0'
        option netmask '255.255.255.0'

**/etc/config/dhcp** :
config dnsmasq
        option domainneeded '1'
        option boguspriv '1'
        option filterwin2k '0'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/wlan/'
        option domain 'wlan'
        option expandhosts '1'
        option nonegcache '0'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.auto'

config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option dhcpv6 'server'
        option ra 'server'

config dhcp 'wlan0'
        option interface 'wlan0'
        option start '100'
        option limit '150'
        option leasetime '12h'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'

**Comment by mantas-p** [comment]
Hi,

You have you ```lan``` and ```wlan0``` interfaces in the same subnet ```192.168.1.0/24```. This can't work. 
If you want ```lan``` and ```wlan0``` to be on same subnet you need add them to bridge(```br-lan```). Default configuration does exactly this.
