### ISSUE TITLE
Доступно каждомуому

### ISSUE THREAD

**Issue by Kardanj** [8devices/carambola2#79]
Супер, не выходит из головы! 
![IMG_20240530_001910](https://github.com/8devices/carambola2/assets/171403713/0d31269f-ff8c-4e85-9568-8d54bc2db8e8)

**Comment by Kardanj** [comment]
Пойдёт?

**Comment by Kardanj** [comment]
Оригинально! Правда!?

**Comment by Kardanj** [comment]
Что заказали, то и  получите)

**Comment by Kardanj** [comment]
Прежде чем давать сделать , мне то же сообщитедля выполнения не забывайте само задание

**Comment by valinskas** [comment]
Spam. Closed.
